name: Run Pokemon Issue Job

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC)에 실행
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  run-pokemon-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: jdk
        distribution: 'temurin'  # Temurin은 Adoptium의 후속 프로젝트입니다.

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install maven

    - name: Build and run the Java application
      run: |
        mvn clean install
        mvn exec:java -X 
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub Token을 비밀 환경 변수로 설정